export const initial_cards = [
    {}, /* blank card for adding card  */
    {
    'img': '/images/cards/SaintsRow.jpg',
    'category': ['Action', 'RPG'],
    'name': 'Saints Row',
    'rating': 0,
    'voted': '0',
    'description': 'Platinum Edition',
    'oldPrice': '$1,299',
    'newPrice': '$649',
    'discount': '-50%'   
    },
    {
        'img': '../images/cards/Paladins.jpg',
        'category': ['Multiplayer', 'RPG'],
        'name': 'Paladins',
        'rating': 4,
        'voted': '1,820',
        'description': 'Get the Captain Price Operator included with purchase',
        'oldPrice': '',
        'newPrice': 'Free',
        'discount': '' 
    },
     {
        'img': '../images/cards/FarCry6.jpg',
        'category': ['Action'],
        'name': 'Far Cry 6',
        'rating': 4,
        'voted': '2,888',
        'description': 'In-Game Content',
        'oldPrice': '$1,299',
        'newPrice': '$649',
        'discount': '-50%'
    },
    {
        'img': '../images/cards/CallofDute.jpg',
        'category': ['Shooter'],
        'name': 'Call of Duty: Warzone',
        'rating': 3,
        'voted': '18,982',
        'description': 'Get the Captain Price Operator included with purchase',
        'oldPrice': '$1,299',
        'newPrice': '$649',
        'discount': '-50%'
    },
     {
        'img': '../images/cards/WorldofWarcraft.jpg',
        'category': ['Action'],
        'name': 'World of Warcraft: Shadowlands',
        'rating': 3.5,
        'voted': '299',
        'description': 'Includes access to World of Warcraft, Burning Crusade Classic, and WoW Classic!',
        'oldPrice': '',
        'newPrice': 'Free',
        'discount': ''
    },
     {
        'img': '../images/cards/Fortnite.jpg',
        'category': ['Shooter'],
        'name': 'Fortnite',
        'rating': 4.5,
        'voted': '9.199',
        'description': 'Get the Captain Price Operator included with purchase',
        'oldPrice': '$1,299',
        'newPrice': '$649',
        'discount': '-50%'
    },
    {
        'img': '../images/cards/Horizon.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Horizon: Forbidden West',
        'rating': 4.5,
        'voted': '9.199',
        'description': 'Platinum Edition',
        'oldPrice': '$1,299',
        'newPrice': '$649',
        'discount': ''
    },
     {
        'img': '../images/cards/NeedforSpeed.jpg',
        'category': ['Action'],
        'name': 'Need for Speed: Heat',
        'rating': 4.5,
        'voted': '2,911',
        'description': 'Includes access to World of Warcraft, Burning Crusade Classic, and WoW Classic!',
        'oldPrice': '',
        'newPrice': '$649',
        'discount': ''
    },
     {
        'img': '../images/cards/SpiderManMilesMarales.jpg',
        'category': ['Action'],
        'name': 'Spider-Man: Miles Morales',
        'rating': 4,
        'voted': '920',
        'description': 'Get the Captain Price Operator included with purchase',
        'oldPrice': '$1,299',
        'newPrice': '$649',
        'discount': '-50%'
    },
     {
        'img': '../images/cards/Witcher.jpg',
        'category': ['Card', 'Game'],
        'name': 'Witcher 3: Wild Hunt',
        'rating': 5,
        'voted': '299,890',
        'description': 'Will only be usable in the new Classic Format when it is released',
        'oldPrice': '$1,299',
        'newPrice': '$649',
        'discount': ''
    },
    {
        'img': '../images/cards/CuardiansoftheGalaxy.jpg',
        'category': ['Shooter'],
        'name': 'Guardians of the Galaxy',
        'rating': 3,
        'voted': '29',
        'description': 'In-Game Content',
        'oldPrice': '$1,299',
        'newPrice': '$649',
        'discount': '-50%'
    },
     {
        'img': '../images/cards/CrashTeamRacing.jpg',
        'category': ['Shooter'],
        'name': 'Crash Team Racing',
        'rating': 4.5,
        'voted': '29',
        'description': 'Get the Captain Price Operator included with purchase',
        'oldPrice': '$1,299',
        'newPrice': '$649',
        'discount': '-50%'
    },
    {
        'img': '../images/cards/SpiderMan.jpg',
        'category': ['Multiplayer', 'RPG'],
        'name': 'Spider Man',
        'rating': 4.5,
        'voted': '9.199',
        'description': ' Includes access to World of Warcraft, Burning Crusade Classic, and WoW Classic!',
        'oldPrice': '',
        'newPrice': '$649',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '0',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    },
    {
        'img': '../images/cards/placeholder.jpg',
        'category': ['Action', 'RPG'],
        'name': 'Dragon Age 5',
        'rating': 0,
        'voted': '',
        'description': 'Non released',
        'oldPrice': '',
        'newPrice': '',
        'discount': ''
    }

  ];